name = "NIFTy"
uuid = "6ab242ad-4386-469b-b253-7bd36a93f0aa"
authors = ["Philipp Haim <philipp.haim@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
